// This is an autogenerated file from Firebase Studio.

'use server';
/**
 * @fileOverview A product recommendation AI agent.
 *
 * - recommendProducts - A function that handles the product recommendation process.
 * - RecommendProductsInput - The input type for the recommendProducts function.
 * - RecommendProductsOutput - The return type for the recommendProducts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendProductsInputSchema = z.object({
  browsingHistory: z.string().describe('The browsing history of the user.'),
  purchaseHistory: z.string().describe('The purchase history of the user.'),
});
export type RecommendProductsInput = z.infer<typeof RecommendProductsInputSchema>;

const RecommendProductsOutputSchema = z.object({
  recommendedProducts: z.array(
    z.string().describe('The list of recommended products based on user history.')
  ).describe('List of recommended products.'),
});
export type RecommendProductsOutput = z.infer<typeof RecommendProductsOutputSchema>;

export async function recommendProducts(input: RecommendProductsInput): Promise<RecommendProductsOutput> {
  return recommendProductsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendProductsPrompt',
  input: {schema: RecommendProductsInputSchema},
  output: {schema: RecommendProductsOutputSchema},
  prompt: `You are an e-commerce expert specializing in product recommendations.

Based on the user's browsing history and purchase history, you will generate a list of recommended products that they might be interested in.

Consider the user's past behavior and preferences to provide personalized recommendations.

Browsing History: {{{browsingHistory}}}
Purchase History: {{{purchaseHistory}}}

Recommended Products:`,
});

const recommendProductsFlow = ai.defineFlow(
  {
    name: 'recommendProductsFlow',
    inputSchema: RecommendProductsInputSchema,
    outputSchema: RecommendProductsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
