
export interface Product {
    id: string
    name: string
    brand: string
    category: string
    price: number
    originalPrice?: number
    image: string
    description: string
    specs?: string[]
}


export const products: Product[] = [
  // MOBILE PHONES - iPhone (Updated with iPhone 17 Pro Max)
  {
    id: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    brand: "apple",
    category: "phones",
    price: 209999,
    originalPrice: 229999,
    image: "/products/iphone-17-pro-max.jpg",
    description: "The next generation of iPhone. Featuring the A19 Pro chip, ultra-advanced titanium build, and a revolutionary 4-lens camera system with AI-enhanced optics.",
    specs: [
      "6.9-inch ProMotion Ultra Display",
      "A19 Pro chip with next-gen Neural Engine",
      "4-lens camera system (48MP Main, 48MP Telephoto, 48MP Wide, 12MP Macro)",
      "Ultra-Fast WiFi 7 & 6G Ready",
      "MagSafe with 50W fast charging",
      "Up to 2TB storage capacity",
    ],
  },
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    brand: "apple",
    category: "phones",
    price: 189999,
    originalPrice: 209999,
    image: "/products/iphone-16-pro-max.jpg",
    description: "The most advanced iPhone with titanium design, A18 Pro chip, and revolutionary camera system.",
    specs: [
      "6.9-inch Super Retina XDR display",
      "A18 Pro chip with 6-core GPU",
      "Pro camera system (48MP Main, 48MP Ultra Wide, 12MP Telephoto)",
      "Up to 33 hours video playback",
      "Titanium design with Camera Control",
      "1TB storage option",
    ],
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    brand: "apple",
    category: "phones",
    price: 129999,
    originalPrice: 149999,
    image: "/products/iphone-16.jpg",
    description: "Latest iPhone with A18 chip, Camera Control, and vibrant color options.",
    specs: [
      "6.1-inch Super Retina XDR display",
      "A18 chip with 5-core GPU",
      "Advanced dual camera system (48MP Main, 12MP Ultra Wide)",
      "Up to 22 hours video playback",
      "Aluminum design",
      "128GB storage option",
    ],
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "apple",
    category: "phones",
    price: 159999,
    originalPrice: 179999,
    image: "/products/iphone-15-pro-max.jpg",
    description: "Previous generation Pro Max with titanium design and A17 Pro chip.",
    specs: [
      "6.7-inch Super Retina XDR display",
      "A17 Pro chip with 6-core GPU",
      "Pro camera system (48MP Main, 48MP Ultra Wide, 12MP Telephoto)",
      "Up to 29 hours video playback",
      "Titanium design",
      "1TB storage option",
    ],
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "apple",
    category: "phones",
    price: 139999,
    originalPrice: 159999,
    image: "/products/iphone-15-pro.jpg",
    description: "Pro iPhone with A17 Pro chip and titanium construction.",
    specs: [
      "6.1-inch Super Retina XDR display",
      "A17 Pro chip with 6-core GPU",
      "Pro camera system (48MP Main, 48MP Ultra Wide, 12MP Telephoto)",
      "Up to 23 hours video playback",
      "Titanium design",
      "512GB storage option",
    ],
  },
  {
    id: "iphone-14-pro-max",
    name: "iPhone 14 Pro Max",
    brand: "apple",
    category: "phones",
    price: 129999,
    originalPrice: 149999,
    image: "/products/iphone-14-pro-max.jpg",
    description: "iPhone 14 Pro Max with Dynamic Island and A16 Bionic chip.",
    specs: [
      "6.7-inch Super Retina XDR display with Dynamic Island",
      "A16 Bionic chip",
      "Pro camera system (48MP Main, 12MP Ultra Wide, 12MP Telephoto)",
      "Up to 29 hours video playback",
      "Stainless steel design",
      "1TB storage option",
    ],
  },
  {
    id: "iphone-13-pro-max",
    name: "iPhone 13 Pro Max",
    brand: "apple",
    category: "phones",
    price: 109999,
    originalPrice: 129999,
    image: "/products/iphone-13-pro-max.jpg",
    description: "iPhone 13 Pro Max with ProMotion display and A15 Bionic chip.",
    specs: [
      "6.7-inch Super Retina XDR display with ProMotion",
      "A15 Bionic chip",
      "Pro camera system (12MP Main, 12MP Ultra Wide, 12MP Telephoto)",
      "Up to 28 hours video playback",
      "Stainless steel design",
      "1TB storage option",
    ],
  },
  {
    id: "iphone-12-pro-max",
    name: "iPhone 12 Pro Max",
    brand: "apple",
    category: "phones",
    price: 89999,
    originalPrice: 109999,
    image: "/products/iphone-12-pro-max.jpg",
    description: "iPhone 12 Pro Max with 5G capability and A14 Bionic chip.",
    specs: [
      "6.7-inch Super Retina XDR display",
      "A14 Bionic chip",
      "Pro camera system (12MP Main, 12MP Ultra Wide, 12MP Telephoto)",
      "Up to 20 hours video playback",
      "Stainless steel design",
      "512GB storage option",
    ],
  },

  // MOBILE PHONES - Samsung (Updated with S26 Ultra)
  {
    id: "samsung-galaxy-s26-ultra",
    name: "Samsung Galaxy S26 Ultra",
    brand: "samsung",
    category: "phones",
    price: 219999,
    originalPrice: 239999,
    image: "/products/samsung-galaxy-s26-ultra.jpg",
    description: "The pinnacle of mobile engineering. Featuring Galaxy AI 2.0, a 300MP main sensor, and the lightning-fast Snapdragon 8 Gen 5 for unprecedented power.",
    specs: [
      "6.8-inch Dynamic AMOLED 3X 144Hz display",
      "Snapdragon 8 Gen 5 Made for Galaxy",
      "300MP quad camera system with 200x Space Zoom",
      "6000mAh battery with 65W charging",
      "Integrated S Pen with sub-1ms latency",
      "Galaxy AI 2.0 with Real-time Multitasking",
    ],
  },
  {
    id: "samsung-galaxy-s25-ultra",
    name: "Samsung Galaxy S25 Ultra",
    brand: "samsung",
    category: "phones",
    price: 199999,
    originalPrice: 219999,
    image: "/products/samsung-galaxy-s25-ultra.jpg",
    description: "Ultimate Android flagship with S Pen, AI features, and 200MP camera system.",
    specs: [
      "6.8-inch Dynamic AMOLED 2X display",
      "Snapdragon 8 Gen 4 processor",
      "200MP quad camera system with AI zoom",
      "5000mAh battery with 45W fast charging",
      "Built-in S Pen with AI features",
      "1TB storage option",
    ],
  },
  {
    id: "samsung-galaxy-s24-plus",
    name: "Samsung Galaxy S24+",
    brand: "samsung",
    category: "phones",
    price: 149999,
    originalPrice: 169999,
    image: "/products/samsung-galaxy-s24-plus.jpg",
    description: "Large display Galaxy with premium features and AI capabilities.",
    specs: [
      "6.7-inch Dynamic AMOLED 2X display",
      "Snapdragon 8 Gen 3 processor",
      "50MP triple camera system",
      "4900mAh battery with 45W fast charging",
      "AI-powered features",
      "512GB storage option",
    ],
  },
  {
    id: "samsung-galaxy-s24",
    name: "Samsung Galaxy S24 Ultra",
    brand: "samsung",
    category: "phones",
    price: 119999,
    originalPrice: 139999,
    image: "/products/samsung-galaxy-s24.jpg",
    description: "Galaxy S24 Ultra with AI features and S Pen functionality.",
    specs: [
      "6.8-inch Dynamic AMOLED 2X display",
      "Snapdragon 8 Gen 3 processor",
      "200MP quad camera system",
      "5000mAh battery with 45W fast charging",
      "Built-in S Pen",
      "1TB storage option",
    ],
  },
  {
    id: "samsung-galaxy-s24-fe",
    name: "Samsung Galaxy S24 FE",
    brand: "samsung",
    category: "phones",
    price: 89999,
    originalPrice: 109999,
    image: "/products/samsung-galaxy-s24-fe.jpg",
    description: "Fan Edition with flagship features at accessible price.",
    specs: [
      "6.7-inch Dynamic AMOLED 2X display",
      "Exynos 2400e processor",
      "50MP triple camera system",
      "4700mAh battery with 25W fast charging",
      "IP68 water resistance",
      "256GB storage option",
    ],
  },
  {
    id: "samsung-galaxy-fold6",
    name: "Samsung Galaxy Z Fold6",
    brand: "samsung",
    category: "phones",
    price: 249999,
    originalPrice: 279999,
    image: "/products/samsung-galaxy-fold6.jpg",
    description: "Revolutionary foldable phone with dual displays and S Pen support.",
    specs: [
      "7.6-inch main display, 6.3-inch cover display",
      "Snapdragon 8 Gen 3 processor",
      "50MP triple camera system",
      "4400mAh battery with 25W fast charging",
      "S Pen support",
      "1TB storage option",
    ],
  },
  {
    id: "samsung-galaxy-flip6",
    name: "Samsung Galaxy Z Flip6",
    brand: "samsung",
    category: "phones",
    price: 159999,
    originalPrice: 179999,
    image: "/products/samsung-galaxy-flip6.jpg",
    description: "Compact foldable with improved cameras and battery life.",
    specs: [
      "6.7-inch main display, 3.4-inch cover display",
      "Snapdragon 8 Gen 3 processor",
      "50MP dual camera system",
      "4000mAh battery with 25W fast charging",
      "Compact foldable design",
      "512GB storage option",
    ],
  },
  {
    id: "samsung-galaxy-a55",
    name: "Samsung Galaxy A55 5G",
    brand: "samsung",
    category: "phones",
    price: 54999,
    originalPrice: 64999,
    image: "/products/samsung-galaxy-a55.jpg",
    description: "Mid-range Galaxy with 5G connectivity and great cameras.",
    specs: [
      "6.6-inch Super AMOLED display",
      "Exynos 1480 processor",
      "50MP triple camera system",
      "5000mAh battery with 25W fast charging",
      "5G connectivity",
      "256GB storage option",
    ],
  },
  {
    id: "samsung-galaxy-a35",
    name: "Samsung Galaxy A35 5G",
    brand: "samsung",
    category: "phones",
    price: 39999,
    originalPrice: 49999,
    image: "/products/samsung-galaxy-a35.jpg",
    description: "Affordable Galaxy with premium features and 5G support.",
    specs: [
      "6.6-inch Super AMOLED display",
      "Exynos 1380 processor",
      "50MP triple camera system",
      "5000mAh battery with 25W fast charging",
      "5G connectivity",
      "128GB storage option",
    ],
  },

  // MOBILE PHONES - OnePlus (9 products)
  {
    id: "oneplus-13",
    name: "OnePlus 13",
    brand: "oneplus",
    category: "phones",
    price: 119999,
    originalPrice: 139999,
    image: "/products/oneplus-13.jpg",
    description: "Latest OnePlus flagship with ultra-fast charging and premium build.",
    specs: [
      "6.82-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 4 processor",
      "50MP Hasselblad camera system",
      "6000mAh battery with 100W charging",
      "OxygenOS 15 based on Android 15",
      "512GB storage option",
    ],
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    brand: "oneplus",
    category: "phones",
    price: 89999,
    originalPrice: 109999,
    image: "/products/oneplus-12.jpg",
    description: "OnePlus 12 with flagship performance and fast charging.",
    specs: [
      "6.82-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 3 processor",
      "50MP Hasselblad camera system",
      "5400mAh battery with 100W charging",
      "OxygenOS 14 based on Android 14",
      "512GB storage option",
    ],
  },
  {
    id: "oneplus-12r",
    name: "OnePlus 12R",
    brand: "oneplus",
    category: "phones",
    price: 69999,
    originalPrice: 84999,
    image: "/products/oneplus-12r.jpg",
    description: "Performance-focused OnePlus with flagship features at lower price.",
    specs: [
      "6.78-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 2 processor",
      "50MP triple camera system",
      "5500mAh battery with 100W charging",
      "OxygenOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "oneplus-11-pro",
    name: "OnePlus 11 Pro",
    brand: "oneplus",
    category: "phones",
    price: 79999,
    originalPrice: 99999,
    image: "/products/oneplus-11-pro.jpg",
    description: "OnePlus 11 Pro with Hasselblad cameras and premium design.",
    specs: [
      "6.7-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 2 processor",
      "50MP Hasselblad triple camera system",
      "5000mAh battery with 100W SuperVOOC charging",
      "OxygenOS 13 based on Android 13",
      "512GB storage option",
    ],
  },
  {
    id: "oneplus-11",
    name: "OnePlus 11",
    brand: "oneplus",
    category: "phones",
    price: 64999,
    originalPrice: 79999,
    image: "/products/oneplus-11.jpg",
    description: "OnePlus 11 with Snapdragon 8 Gen 2 and Hasselblad cameras.",
    specs: [
      "6.7-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 2 processor",
      "50MP Hasselblad camera system",
      "5000mAh battery with 100W charging",
      "OxygenOS 13 based on Android 13",
      "256GB storage option",
    ],
  },
  {
    id: "oneplus-nord-4",
    name: "OnePlus Nord 4",
    brand: "oneplus",
    category: "phones",
    price: 44999,
    originalPrice: 54999,
    image: "/products/oneplus-nord-4.jpg",
    description: "Mid-range OnePlus with premium features and 5G connectivity.",
    specs: [
      "6.74-inch AMOLED display",
      "Snapdragon 7+ Gen 3 processor",
      "50MP dual camera system",
      "5500mAh battery with 100W charging",
      "OxygenOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "oneplus-nord-ce-4",
    name: "OnePlus Nord CE 4",
    brand: "oneplus",
    category: "phones",
    price: 34999,
    originalPrice: 42999,
    image: "/products/oneplus-nord-ce-4.jpg",
    description: "Affordable OnePlus with good performance and cameras.",
    specs: [
      "6.7-inch AMOLED display",
      "Snapdragon 7 Gen 3 processor",
      "50MP dual camera system",
      "5500mAh battery with 100W charging",
      "OxygenOS 14 based on Android 14",
      "128GB storage option",
    ],
  },

  // MOBILE PHONES - Xiaomi (9 products)
  {
    id: "xiaomi-15-ultra",
    name: "Xiaomi 15 Ultra",
    brand: "xiaomi",
    category: "phones",
    price: 149999,
    originalPrice: 169999,
    image: "/products/xiaomi-15-ultra.jpg",
    description: "Xiaomi's flagship with Leica cameras and Snapdragon 8 Gen 4.",
    specs: [
      "6.73-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 4 processor",
      "50MP Leica quad camera system",
      "5300mAh battery with 90W fast charging",
      "MIUI 16 based on Android 15",
      "1TB storage option",
    ],
  },
  {
    id: "xiaomi-15-pro",
    name: "Xiaomi 15 Pro",
    brand: "xiaomi",
    category: "phones",
    price: 119999,
    originalPrice: 139999,
    image: "/products/xiaomi-15-pro.jpg",
    description: "Pro Xiaomi with advanced cameras and premium build quality.",
    specs: [
      "6.73-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 4 processor",
      "50MP Leica triple camera system",
      "4880mAh battery with 120W fast charging",
      "MIUI 16 based on Android 15",
      "512GB storage option",
    ],
  },
  {
    id: "xiaomi-15",
    name: "Xiaomi 15",
    brand: "xiaomi",
    category: "phones",
    price: 89999,
    originalPrice: 109999,
    image: "/products/xiaomi-15.jpg",
    description: "Latest Xiaomi flagship with Snapdragon 8 Gen 4 and Leica cameras.",
    specs: [
      "6.36-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 4 processor",
      "50MP Leica triple camera system",
      "4610mAh battery with 90W fast charging",
      "MIUI 16 based on Android 15",
      "256GB storage option",
    ],
  },
  {
    id: "xiaomi-14-ultra",
    name: "Xiaomi 14 Ultra",
    brand: "xiaomi",
    category: "phones",
    price: 129999,
    originalPrice: 149999,
    image: "/products/xiaomi-14-ultra.jpg",
    description: "Photography-focused flagship with 1-inch main sensor.",
    specs: [
      "6.73-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 3 processor",
      "50MP Leica quad camera system with 1-inch sensor",
      "5300mAh battery with 90W fast charging",
      "MIUI 15 based on Android 14",
      "1TB storage option",
    ],
  },
  {
    id: "xiaomi-14-pro",
    name: "Xiaomi 14 Pro",
    brand: "xiaomi",
    category: "phones",
    price: 99999,
    originalPrice: 119999,
    image: "/products/xiaomi-14-pro.jpg",
    description: "Xiaomi 14 Pro with Leica cameras and premium features.",
    specs: [
      "6.73-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 3 processor",
      "50MP Leica triple camera system",
      "4880mAh battery with 120W fast charging",
      "MIUI 15 based on Android 14",
      "512GB storage option",
    ],
  },
  {
    id: "xiaomi-14",
    name: "Xiaomi 14",
    brand: "xiaomi",
    category: "phones",
    price: 74999,
    originalPrice: 89999,
    image: "/products/xiaomi-14.jpg",
    description: "Compact flagship with Snapdragon 8 Gen 3 and Leica cameras.",
    specs: [
      "6.36-inch LTPO AMOLED display",
      "Snapdragon 8 Gen 3 processor",
      "50MP Leica triple camera system",
      "4610mAh battery with 90W fast charging",
      "MIUI 15 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "redmi-note-14-pro",
    name: "Redmi Note 14 Pro",
    brand: "xiaomi",
    category: "phones",
    price: 39999,
    originalPrice: 49999,
    image: "/products/redmi-note-14-pro.jpg",
    description: "Mid-range Redmi with flagship features and great value.",
    specs: [
      "6.67-inch AMOLED display",
      "Snapdragon 7s Gen 3 processor",
      "200MP triple camera system",
      "5110mAh battery with 120W fast charging",
      "MIUI 15 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "redmi-note-14",
    name: "Redmi Note 14",
    brand: "xiaomi",
    category: "phones",
    price: 29999,
    originalPrice: 37999,
    image: "/products/redmi-note-14.jpg",
    description: "Affordable Redmi with good performance and cameras.",
    specs: [
      "6.67-inch AMOLED display",
      "Snapdragon 685 processor",
      "108MP triple camera system",
      "5110mAh battery with 33W fast charging",
      "MIUI 15 based on Android 14",
      "128GB storage option",
    ],
  },
  {
    id: "poco-f6-pro",
    name: "POCO F6 Pro",
    brand: "xiaomi",
    category: "phones",
    price: 54999,
    originalPrice: 64999,
    image: "/products/poco-f6-pro.jpg",
    description: "Gaming-focused POCO with flagship performance at affordable price.",
    specs: [
      "6.67-inch AMOLED display with 120Hz",
      "Snapdragon 8 Gen 2 processor",
      "50MP triple camera system",
      "5000mAh battery with 120W fast charging",
      "MIUI for POCO based on Android 14",
      "512GB storage option",
    ],
  },

  // MOBILE PHONES - Tecno (9 products)
  {
    id: "tecno-phantom-v-fold2",
    name: "Tecno Phantom V Fold2",
    brand: "tecno",
    category: "phones",
    price: 179999,
    originalPrice: 199999,
    image: "/products/tecno-phantom-v-fold2.jpg",
    description: "Premium foldable phone with dual displays and flagship features.",
    specs: [
      "7.85-inch main display, 6.42-inch cover display",
      "MediaTek Dimensity 9000+ processor",
      "50MP triple camera system",
      "5000mAh battery with 45W fast charging",
      "HiOS 14 based on Android 14",
      "512GB storage option",
    ],
  },
  {
    id: "tecno-phantom-v-flip2",
    name: "Tecno Phantom V Flip2",
    brand: "tecno",
    category: "phones",
    price: 89999,
    originalPrice: 109999,
    image: "/products/tecno-phantom-v-flip2.jpg",
    description: "Compact foldable with stylish design and good cameras.",
    specs: [
      "6.9-inch main display, 1.32-inch cover display",
      "MediaTek Dimensity 8050 processor",
      "64MP dual camera system",
      "4000mAh battery with 45W fast charging",
      "HiOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "tecno-camon-30-pro",
    name: "Tecno Camon 30 Pro 5G",
    brand: "tecno",
    category: "phones",
    price: 44999,
    originalPrice: 54999,
    image: "/products/tecno-camon-30-pro.jpg",
    description: "Camera-focused phone with AI photography features.",
    specs: [
      "6.78-inch AMOLED display",
      "MediaTek Dimensity 8050 processor",
      "50MP triple camera system with AI",
      "5000mAh battery with 70W fast charging",
      "HiOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "tecno-spark-20-pro",
    name: "Tecno Spark 20 Pro+",
    brand: "tecno",
    category: "phones",
    price: 24999,
    originalPrice: 32999,
    image: "/products/tecno-spark-20-pro.jpg",
    description: "Budget-friendly phone with good performance and cameras.",
    specs: [
      "6.78-inch IPS display",
      "MediaTek Helio G99 processor",
      "108MP dual camera system",
      "5000mAh battery with 33W fast charging",
      "HiOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "tecno-pova-6-pro",
    name: "Tecno Pova 6 Pro 5G",
    brand: "tecno",
    category: "phones",
    price: 34999,
    originalPrice: 42999,
    image: "/products/tecno-pova-6-pro.jpg",
    description: "Gaming phone with large battery and powerful processor.",
    specs: [
      "6.78-inch AMOLED display with 120Hz",
      "MediaTek Dimensity 6080 processor",
      "108MP triple camera system",
      "6000mAh battery with 70W fast charging",
      "HiOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "tecno-camon-20-premier",
    name: "Tecno Camon 20 Premier 5G",
    brand: "tecno",
    category: "phones",
    price: 39999,
    originalPrice: 49999,
    image: "/products/tecno-camon-20-premier.jpg",
    description: "Premium Camon with advanced camera system and 5G.",
    specs: [
      "6.67-inch AMOLED display",
      "MediaTek Dimensity 8050 processor",
      "50MP RGBW main camera with OIS",
      "5000mAh battery with 45W fast charging",
      "HiOS 13 based on Android 13",
      "512GB storage option",
    ],
  },
  {
    id: "tecno-phantom-x2-pro",
    name: "Tecno Phantom X2 Pro 5G",
    brand: "tecno",
    category: "phones",
    price: 64999,
    originalPrice: 79999,
    image: "/products/tecno-phantom-x2-pro.jpg",
    description: "Flagship Tecno with premium build and advanced cameras.",
    specs: [
      "6.8-inch AMOLED curved display",
      "MediaTek Dimensity 9000 processor",
      "50MP triple camera system with portrait lens",
      "5160mAh battery with 45W fast charging",
      "HiOS 13 based on Android 13",
      "256GB storage option",
    ],
  },
  {
    id: "tecno-spark-go-2024",
    name: "Tecno Spark Go 2024",
    brand: "tecno",
    category: "phones",
    price: 14999,
    originalPrice: 19999,
    image: "/products/tecno-spark-go-2024.jpg",
    description: "Entry-level smartphone with essential features and good battery.",
    specs: [
      "6.6-inch IPS display",
      "UNISOC Tiger T606 processor",
      "48MP dual camera system",
      "5000mAh battery with 10W charging",
      "HiOS 14 Go based on Android 14 Go",
      "128GB storage option",
    ],
  },
  {
    id: "tecno-pop-8",
    name: "Tecno Pop 8",
    brand: "tecno",
    category: "phones",
    price: 12999,
    originalPrice: 16999,
    image: "/products/tecno-pop-8.jpg",
    description: "Ultra-affordable smartphone for basic usage and communication.",
    specs: [
      "6.6-inch IPS display",
      "UNISOC Tiger T606 processor",
      "48MP main camera",
      "5000mAh battery with 10W charging",
      "HiOS 14 Go based on Android 14 Go",
      "64GB storage option",
    ],
  },

  // MOBILE PHONES - Infinix (9 products)
  {
    id: "infinix-zero-40-5g",
    name: "Infinix Zero 40 5G",
    brand: "infinix",
    category: "phones",
    price: 54999,
    originalPrice: 64999,
    image: "/products/infinix-zero-40-5g.jpg",
    description: "Flagship Infinix with 5G connectivity and premium cameras.",
    specs: [
      "6.78-inch AMOLED curved display",
      "MediaTek Dimensity 8200 Ultimate processor",
      "108MP OIS triple camera system",
      "5000mAh battery with 45W fast charging",
      "XOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "infinix-note-40-pro",
    name: "Infinix Note 40 Pro+ 5G",
    brand: "infinix",
    category: "phones",
    price: 39999,
    originalPrice: 49999,
    image: "/products/infinix-note-40-pro.jpg",
    description: "Note series with large display and powerful performance.",
    specs: [
      "6.78-inch AMOLED display",
      "MediaTek Dimensity 7020 processor",
      "108MP triple camera system",
      "4600mAh battery with 45W fast charging",
      "XOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "infinix-gt-20-pro",
    name: "Infinix GT 20 Pro",
    brand: "infinix",
    category: "phones",
    price: 44999,
    originalPrice: 54999,
    image: "/products/infinix-gt-20-pro.jpg",
    description: "Gaming-focused phone with RGB lighting and powerful specs.",
    specs: [
      "6.78-inch AMOLED display with 144Hz",
      "MediaTek Dimensity 8050 processor",
      "108MP triple camera system",
      "5000mAh battery with 45W fast charging",
      "XOS 14 based on Android 14",
      "512GB storage option",
    ],
  },
  {
    id: "infinix-hot-50-pro",
    name: "Infinix Hot 50 Pro+",
    brand: "infinix",
    category: "phones",
    price: 29999,
    originalPrice: 37999,
    image: "/products/infinix-hot-50-pro.jpg",
    description: "Mid-range Hot series with good cameras and battery life.",
    specs: [
      "6.78-inch AMOLED display",
      "MediaTek Helio G100 processor",
      "108MP dual camera system",
      "4000mAh battery with 33W fast charging",
      "XOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "infinix-smart-8-hd",
    name: "Infinix Smart 8 HD",
    brand: "infinix",
    category: "phones",
    price: 16999,
    originalPrice: 21999,
    image: "/products/infinix-smart-8-hd.jpg",
    description: "Budget smartphone with essential features and good build quality.",
    specs: [
      "6.6-inch IPS display",
      "UNISOC Tiger T606 processor",
      "48MP dual camera system",
      "5000mAh battery with 10W charging",
      "XOS 14 based on Android 14 Go",
      "128GB storage option",
    ],
  },
  {
    id: "infinix-zero-30-5g",
    name: "Infinix Zero 30 5G",
    brand: "infinix",
    category: "phones",
    price: 49999,
    originalPrice: 59999,
    image: "/products/infinix-zero-30-5g.jpg",
    description: "Previous generation flagship with 5G and premium features.",
    specs: [
      "6.78-inch AMOLED curved display",
      "MediaTek Dimensity 8020 processor",
      "108MP OIS triple camera system",
      "5000mAh battery with 68W fast charging",
      "XOS 13 based on Android 13",
      "256GB storage option",
    ],
  },
  {
    id: "infinix-note-30-vip",
    name: "Infinix Note 30 VIP",
    brand: "infinix",
    category: "phones",
    price: 34999,
    originalPrice: 42999,
    image: "/products/infinix-note-30-vip.jpg",
    description: "VIP edition Note with premium features and fast charging.",
    specs: [
      "6.67-inch AMOLED display",
      "MediaTek Dimensity 8050 processor",
      "108MP triple camera system",
      "4500mAh battery with 68W fast charging",
      "XOS 13 based on Android 13",
      "256GB storage option",
    ],
  },
  {
    id: "infinix-hot-40-pro",
    name: "Infinix Hot 40 Pro",
    brand: "infinix",
    category: "phones",
    price: 24999,
    originalPrice: 31999,
    image: "/products/infinix-hot-40-pro.jpg",
    description: "Affordable Hot series with good performance and cameras.",
    specs: [
      "6.78-inch IPS display",
      "MediaTek Helio G88 processor",
      "108MP dual camera system",
      "5000mAh battery with 33W fast charging",
      "XOS 13 based on Android 13",
      "256GB storage option",
    ],
  },
  {
    id: "infinix-smart-8-plus",
    name: "Infinix Smart 8 Plus",
    brand: "infinix",
    category: "phones",
    price: 19999,
    originalPrice: 24999,
    image: "/products/infinix-smart-8-plus.jpg",
    description: "Enhanced Smart series with better cameras and performance.",
    specs: [
      "6.6-inch IPS display",
      "UNISOC Tiger T606 processor",
      "48MP dual camera system",
      "5000mAh battery with 18W fast charging",
      "XOS 14 based on Android 14",
      "128GB storage option",
    ],
  },

  // MOBILE PHONES - Oppo (9 products)
  {
    id: "oppo-find-x8-pro",
    name: "Oppo Find X8 Pro",
    brand: "oppo",
    category: "phones",
    price: 159999,
    originalPrice: 179999,
    image: "/products/oppo-find-x8-pro.jpg",
    description: "Flagship Oppo with Hasselblad cameras and premium design.",
    specs: [
      "6.82-inch LTPO AMOLED display",
      "MediaTek Dimensity 9400 processor",
      "50MP Hasselblad quad camera system",
      "5400mAh battery with 100W SuperVOOC charging",
      "ColorOS 15 based on Android 15",
      "1TB storage option",
    ],
  },
  {
    id: "oppo-find-x8",
    name: "Oppo Find X8",
    brand: "oppo",
    category: "phones",
    price: 129999,
    originalPrice: 149999,
    image: "/products/oppo-find-x8.jpg",
    description: "Latest Find series with advanced cameras and fast charging.",
    specs: [
      "6.59-inch LTPO AMOLED display",
      "MediaTek Dimensity 9400 processor",
      "50MP Hasselblad triple camera system",
      "5630mAh battery with 80W SuperVOOC charging",
      "ColorOS 15 based on Android 15",
      "512GB storage option",
    ],
  },
  {
    id: "oppo-reno-12-pro",
    name: "Oppo Reno 12 Pro 5G",
    brand: "oppo",
    category: "phones",
    price: 64999,
    originalPrice: 79999,
    image: "/products/oppo-reno-12-pro.jpg",
    description: "Reno series with portrait photography focus and 5G connectivity.",
    specs: [
      "6.7-inch AMOLED curved display",
      "MediaTek Dimensity 7300 processor",
      "50MP triple camera system with portrait lens",
      "5000mAh battery with 80W SuperVOOC charging",
      "ColorOS 14 based on Android 14",
      "512GB storage option",
    ],
  },
  {
    id: "oppo-reno-12",
    name: "Oppo Reno 12 5G",
    brand: "oppo",
    category: "phones",
    price: 49999,
    originalPrice: 59999,
    image: "/products/oppo-reno-12.jpg",
    description: "Mid-range Reno with good cameras and 5G support.",
    specs: [
      "6.7-inch AMOLED display",
      "MediaTek Dimensity 7300 processor",
      "50MP triple camera system",
      "5000mAh battery with 80W SuperVOOC charging",
      "ColorOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "oppo-a3-pro",
    name: "Oppo A3 Pro 5G",
    brand: "oppo",
    category: "phones",
    price: 34999,
    originalPrice: 42999,
    image: "/products/oppo-a3-pro.jpg",
    description: "A-series with 5G connectivity and good battery life.",
    specs: [
      "6.67-inch AMOLED display",
      "MediaTek Dimensity 6300 processor",
      "50MP dual camera system",
      "5000mAh battery with 45W SuperVOOC charging",
      "ColorOS 14 based on Android 14",
      "256GB storage option",
    ],
  },
  {
    id: "oppo-a79-5g",
    name: "Oppo A79 5G",
    brand: "oppo",
    category: "phones",
    price: 29999,
    originalPrice: 37999,
    image: "/products/oppo-a79-5g.jpg",
    description: "Affordable 5G phone with decent performance and cameras.",
    specs: [
      "6.72-inch IPS display",
      "MediaTek Dimensity 6020 processor",
      "50MP dual camera system",
      "5000mAh battery with 33W SuperVOOC charging",
      "ColorOS 14 based on Android 14",
      "128GB storage option",
    ],
  },
  {
    id: "oppo-a18",
    name: "Oppo A18",
    brand: "oppo",
    category: "phones",
    price: 19999,
    originalPrice: 24999,
    image: "/products/oppo-a18.jpg",
    description: "Entry-level Oppo with essential features and good build quality.",
    specs: [
      "6.56-inch IPS display",
      "MediaTek Helio G85 processor",
      "8MP dual camera system",
      "5000mAh battery with 10W charging",
      "ColorOS 13.1 based on Android 13",
      "128GB storage option",
    ],
  },
  {
    id: "oppo-find-n3-flip",
    name: "Oppo Find N3 Flip",
    brand: "oppo",
    category: "phones",
    price: 119999,
    originalPrice: 139999,
    image: "/products/oppo-find-n3-flip.jpg",
    description: "Compact foldable with Hasselblad cameras and premium design.",
    specs: [
      "6.8-inch main display, 3.26-inch cover display",
      "MediaTek Dimensity 9200 processor",
      "50MP Hasselblad triple camera system",
      "4300mAh battery with 44W SuperVOOC charging",
      "ColorOS 14 based on Android 14",
      "512GB storage option",
    ],
  },
  {
    id: "oppo-find-n3",
    name: "Oppo Find N3",
    brand: "oppo",
    category: "phones",
    price: 199999,
    originalPrice: 229999,
    image: "/products/oppo-find-n3.jpg",
    description: "Large foldable with book-style design and Hasselblad cameras.",
    specs: [
      "7.82-inch main display, 6.31-inch cover display",
      "Snapdragon 8 Gen 2 processor",
      "48MP Hasselblad triple camera system",
      "4805mAh battery with 67W SuperVOOC charging",
      "ColorOS 14 based on Android 14",
      "1TB storage option",
    ],
  },

  // MOBILE PHONES - Google (9 products)
  {
    id: "google-pixel-9-pro-xl",
    name: "Google Pixel 9 Pro XL",
    brand: "google",
    category: "phones",
    price: 159999,
    originalPrice: 179999,
    image: "/products/google-pixel-9-pro-xl.jpg",
    description: "Largest Pixel with advanced AI features and exceptional cameras.",
    specs: [
      "6.8-inch LTPO OLED display",
      "Google Tensor G4 chip",
      "50MP triple camera with AI features",
      "5060mAh battery with 30W wireless charging",
      "7 years of OS and security updates",
      "1TB storage option",
    ],
  },
  {
    id: "google-pixel-9-pro",
    name: "Google Pixel 9 Pro",
    brand: "google",
    category: "phones",
    price: 139999,
    originalPrice: 159999,
    image: "/products/google-pixel-9-pro.jpg",
    description: "Pro Pixel with telephoto lens and advanced AI capabilities.",
    specs: [
      "6.3-inch LTPO OLED display",
      "Google Tensor G4 chip",
      "50MP triple camera with AI features",
      "4700mAh battery with 30W wireless charging",
      "7 years of OS and security updates",
      "512GB storage option",
    ],
  },
  {
    id: "google-pixel-9",
    name: "Google Pixel 9",
    brand: "google",
    category: "phones",
    price: 109999,
    originalPrice: 129999,
    image: "/products/google-pixel-9.jpg",
    description: "Latest Pixel with Tensor G4 and pure Android experience.",
    specs: [
      "6.3-inch OLED display",
      "Google Tensor G4 chip",
      "50MP dual camera with AI features",
      "4700mAh battery with 27W fast charging",
      "7 years of OS and security updates",
      "256GB storage option",
    ],
  },
  {
    id: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    brand: "google",
    category: "phones",
    price: 119999,
    originalPrice: 139999,
    image: "/products/google-pixel-8-pro.jpg",
    description: "Previous generation Pro with Tensor G3 and advanced cameras.",
    specs: [
      "6.7-inch LTPO OLED display",
      "Google Tensor G3 chip",
      "50MP triple camera with AI features",
      "5050mAh battery with 30W wireless charging",
      "7 years of OS and security updates",
      "1TB storage option",
    ],
  },
  {
    id: "google-pixel-8",
    name: "Google Pixel 8",
    brand: "google",
    category: "phones",
    price: 89999,
    originalPrice: 109999,
    image: "/products/google-pixel-8.jpg",
    description: "Pixel 8 with Tensor G3 and excellent camera AI.",
    specs: [
      "6.2-inch Actua display",
      "Google Tensor G3 chip",
      "50MP dual camera with AI features",
      "4575mAh battery with 27W fast charging",
      "7 years of OS updates",
      "256GB storage option",
    ],
  },
  {
    id: "google-pixel-8a",
    name: "Google Pixel 8a",
    brand: "google",
    category: "phones",
    price: 64999,
    originalPrice: 79999,
    image: "/products/google-pixel-8a.jpg",
    description: "Affordable Pixel with flagship camera features and Tensor G3.",
    specs: [
      "6.1-inch OLED display",
      "Google Tensor G3 chip",
      "64MP dual camera with AI features",
      "4492mAh battery with 18W fast charging",
      "7 years of OS updates",
      "128GB storage option",
    ],
  },
  {
    id: "google-pixel-fold",
    name: "Google Pixel Fold",
    brand: "google",
    category: "phones",
    price: 219999,
    originalPrice: 249999,
    image: "/products/google-pixel-fold.jpg",
    description: "Google's first foldable with Pixel camera experience.",
    specs: [
      "7.6-inch main display, 5.8-inch cover display",
      "Google Tensor G2 chip",
      "48MP triple camera system",
      "4821mAh battery with 30W fast charging",
      "Android 14 with foldable optimizations",
      "512GB storage option",
    ],
  },
  {
    id: "google-pixel-7-pro",
    name: "Google Pixel 7 Pro",
    brand: "google",
    category: "phones",
    price: 79999,
    originalPrice: 99999,
    image: "/products/google-pixel-7-pro.jpg",
    description: "Pixel 7 Pro with Tensor G2 and telephoto camera.",
    specs: [
      "6.7-inch LTPO OLED display",
      "Google Tensor G2 chip",
      "50MP triple camera system",
      "5000mAh battery with 30W wireless charging",
      "5 years of security updates",
      "512GB storage option",
    ],
  },
  {
    id: "google-pixel-7a",
    name: "Google Pixel 7a",
    brand: "google",
    category: "phones",
    price: 54999,
    originalPrice: 69999,
    image: "/products/google-pixel-7a.jpg",
    description: "Mid-range Pixel with flagship camera features and Tensor G2.",
    specs: [
      "6.1-inch OLED display",
      "Google Tensor G2 chip",
      "64MP dual camera system",
      "4385mAh battery with 18W fast charging",
      "5 years of security updates",
      "128GB storage option",
    ],
  },

  // LAPTOPS - HP (9 products)
  {
    id: "hp-spectre-x360-16",
    name: "HP Spectre x360 16",
    brand: "hp",
    category: "laptops",
    price: 249999,
    originalPrice: 289999,
    image: "/products/hp-spectre-x360-16.jpg",
    description: "Premium 2-in-1 convertible with OLED display and Intel Core Ultra.",
    specs: [
      "16-inch 4K OLED touchscreen",
      "Intel Core Ultra 7 155H processor",
      "32GB LPDDR5X RAM",
      "1TB PCIe SSD",
      "Intel Arc Graphics",
      "Up to 17 hours battery life",
    ],
  },
  {
    id: "hp-envy-x360-15",
    name: "HP Envy x360 15",
    brand: "hp",
    category: "laptops",
    price: 179999,
    originalPrice: 209999,
    image: "/products/hp-envy-x360-15.jpg",
    description: "Versatile 2-in-1 laptop with AMD Ryzen processor and premium build.",
    specs: [
      "15.6-inch FHD touchscreen",
      "AMD Ryzen 7 7730U processor",
      "16GB DDR4 RAM",
      "512GB PCIe SSD",
      "AMD Radeon Graphics",
      "Up to 13 hours battery life",
    ],
  },
  {
    id: "hp-pavilion-15",
    name: "HP Pavilion 15",
    brand: "hp",
    category: "laptops",
    price: 89999,
    originalPrice: 109999,
    image: "/products/hp-pavilion-15.jpg",
    description: "Mid-range laptop with good performance for everyday tasks.",
    specs: [
      "15.6-inch FHD display",
      "Intel Core i5-1335U processor",
      "8GB DDR4 RAM",
      "512GB PCIe SSD",
      "Intel Iris Xe Graphics",
      "Up to 8 hours battery life",
    ],
  },
  {
    id: "hp-omen-16",
    name: "HP OMEN 16",
    brand: "hp",
    category: "laptops",
    price: 199999,
    originalPrice: 239999,
    image: "/products/hp-omen-16.jpg",
    description: "Gaming laptop with RTX graphics and high refresh rate display.",
    specs: [
      "16.1-inch FHD 165Hz display",
      "Intel Core i7-13700HX processor",
      "16GB DDR5 RAM",
      "1TB PCIe SSD",
      "NVIDIA RTX 4060 8GB",
      "RGB backlit keyboard",
    ],
  },
  {
    id: "hp-victus-15",
    name: "HP Victus 15",
    brand: "hp",
    category: "laptops",
    price: 129999,
    originalPrice: 159999,
    image: "/products/hp-victus-15.jpg",
    description: "Entry-level gaming laptop with dedicated graphics.",
    specs: [
      "15.6-inch FHD 144Hz display",
      "AMD Ryzen 5 7535HS processor",
      "8GB DDR5 RAM",
      "512GB PCIe SSD",
      "NVIDIA RTX 4050 6GB",
      "Backlit keyboard",
    ],
  },
  {
    id: "hp-elitebook-840-g10",
    name: "HP EliteBook 840 G10",
    brand: "hp",
    category: "laptops",
    price: 219999,
    originalPrice: 259999,
    image: "/products/hp-elitebook-840-g10.jpg",
    description: "Business laptop with enterprise security and premium build quality.",
    specs: [
      "14-inch FHD display",
      "Intel Core i7-1355U processor",
      "16GB DDR5 RAM",
      "512GB PCIe SSD",
      "Intel Iris Xe Graphics",
      "HP Sure View privacy screen",
    ],
  },
  {
    id: "hp-probook-450-g10",
    name: "HP ProBook 450 G10",
    brand: "hp",
    category: "laptops",
    price: 119999,
    originalPrice: 149999,
    image: "/products/hp-probook-450-g10.jpg",
    description: "Professional laptop with reliable performance and security features.",
    specs: [
      "15.6-inch FHD display",
      "Intel Core i5-1335U processor",
      "8GB DDR4 RAM",
      "256GB PCIe SSD",
      "Intel Iris Xe Graphics",
      "HP Wolf Security",
    ],
  },
  {
    id: "hp-laptop-15s",
    name: "HP Laptop 15s",
    brand: "hp",
    category: "laptops",
    price: 64999,
    originalPrice: 79999,
    image: "/products/hp-laptop-15s.jpg",
    description: "Affordable laptop for basic computing needs and students.",
    specs: [
      "15.6-inch HD display",
      "Intel Core i3-1215U processor",
      "8GB DDR4 RAM",
      "256GB PCIe SSD",
      "Intel UHD Graphics",
      "Up to 7 hours battery life",
    ],
  },
  {
    id: "hp-zbook-studio-g10",
    name: "HP ZBook Studio G10",
    brand: "hp",
    category: "laptops",
    price: 399999,
    originalPrice: 459999,
    image: "/products/hp-zbook-studio-g10.jpg",
    description: "Mobile workstation for creative professionals and engineers.",
    specs: [
      "16-inch 4K DreamColor display",
      "Intel Core i9-13900H processor",
      "32GB DDR5 RAM",
      "1TB PCIe SSD",
      "NVIDIA RTX A2000 8GB",
      "ISV certified applications",
    ],
  },

  // LAPTOPS - Lenovo (9 products)
  {
    id: "lenovo-thinkpad-x1-carbon-gen11",
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    brand: "lenovo",
    category: "laptops",
    price: 289999,
    originalPrice: 329999,
    image: "/products/lenovo-thinkpad-x1-carbon-gen11.jpg",
    description: "Ultra-premium business laptop with carbon fiber construction.",
    specs: [
      "14-inch 2.8K OLED display",
      "Intel Core i7-1365U processor",
      "32GB LPDDR5 RAM",
      "1TB PCIe SSD",
      "Intel Iris Xe Graphics",
      "Up to 28 hours battery life",
    ],
  },
  {
    id: "lenovo-yoga-9i-14",
    name: "Lenovo Yoga 9i 14",
    brand: "lenovo",
    category: "laptops",
    price: 219999,
    originalPrice: 259999,
    image: "/products/lenovo-yoga-9i-14.jpg",
    description: "Premium 2-in-1 convertible with OLED display and Dolby Atmos.",
    specs: [
      "14-inch 4K OLED touchscreen",
      "Intel Core i7-1360P processor",
      "16GB LPDDR5 RAM",
      "1TB PCIe SSD",
      "Intel Iris Xe Graphics",
      "Dolby Atmos speakers",
    ],
  },
  {
    id: "lenovo-legion-5-pro",
    name: "Lenovo Legion 5 Pro",
    brand: "lenovo",
    category: "laptops",
    price: 189999,
    originalPrice: 229999,
    image: "/products/lenovo-legion-5-pro.jpg",
    description: "High-performance gaming laptop with RTX graphics and QHD display.",
    specs: [
      "16-inch QHD 165Hz display",
      "AMD Ryzen 7 7745HX processor",
      "16GB DDR5 RAM",
      "1TB PCIe SSD",
      "NVIDIA RTX 4060 8GB",
      "Legion Coldfront cooling",
    ],
  },
  {
    id: "lenovo-ideapad-5-pro",
    name: "Lenovo IdeaPad 5 Pro",
    brand: "lenovo",
    category: "laptops",
    price: 139999,
    originalPrice: 169999,
    image: "/products/lenovo-ideapad-5-pro.jpg",
    description: "Creator laptop with 2.8K display and powerful performance.",
    specs: [
      "16-inch 2.8K display",
      "AMD Ryzen 7 7735HS processor",
      "16GB DDR5 RAM",
      "512GB PCIe SSD",
      "AMD Radeon 680M Graphics",
      "Up to 12 hours battery life",
    ],
  },
  {
    id: "lenovo-thinkbook-15-g4",
    name: "Lenovo ThinkBook 15 G4",
    brand: "lenovo",
    category: "laptops",
    price: 109999,
    originalPrice: 139999,
    image: "/products/lenovo-thinkbook-15-g4.jpg",
    description: "Business laptop with modern design and reliable performance.",
    specs: [
      "15.6-inch FHD display",
      "Intel Core i5-1235U processor",
      "8GB DDR4 RAM",
      "512GB PCIe SSD",
      "Intel Iris Xe Graphics",
      "Up to 10 hours battery life",
    ],
  },
  {
    id: "lenovo-legion-slim-5",
    name: "Lenovo Legion Slim 5",
    brand: "lenovo",
    category: "laptops",
    price: 159999,
    originalPrice: 189999,
    image: "/products/lenovo-legion-slim-5.jpg",
    description: "Thin gaming laptop with RTX graphics and premium build quality.",
    specs: [
      "16-inch QHD 165Hz display",
      "AMD Ryzen 7 7840HS processor",
      "16GB DDR5 RAM",
      "512GB PCIe SSD",
      "NVIDIA RTX 4050 6GB",
      "Legion AI Engine",
    ],
  },
  {
    id: "lenovo-ideapad-3-15",
    name: "Lenovo IdeaPad 3 15",
    brand: "lenovo",
    category: "laptops",
    price: 74999,
    originalPrice: 94999,
    image: "/products/lenovo-ideapad-3-15.jpg",
    description: "Affordable laptop for everyday computing and productivity.",
    specs: [
      "15.6-inch FHD display",
      "AMD Ryzen 5 5500U processor",
      "8GB DDR4 RAM",
      "256GB PCIe SSD",
      "AMD Radeon Graphics",
      "Up to 8 hours battery life",
    ],
  },
  {
    id: "lenovo-thinkpad-e15-gen4",
    name: "Lenovo ThinkPad E15 Gen 4",
    brand: "lenovo",
    category: "laptops",
    price: 129999,
    originalPrice: 159999,
    image: "/products/lenovo-thinkpad-e15-gen4.jpg",
    description: "Entry-level ThinkPad with business features and durability.",
    specs: [
      "15.6-inch FHD display",
      "Intel Core i5-1235U processor",
      "8GB DDR4 RAM",
      "256GB PCIe SSD",
      "Intel Iris Xe Graphics",
      "ThinkPad TrackPoint",
    ],
  },
  {
    id: "lenovo-yoga-slim-7-pro",
    name: "Lenovo Yoga Slim 7 Pro",
    brand: "lenovo",
    category: "laptops",
    price: 179999,
    originalPrice: 219999,
    image: "/products/lenovo-yoga-slim-7-pro.jpg",
    description: "Slim creator laptop with 2.8K display and powerful performance.",
    specs: [
      "14.5-inch 2.8K display",
      "AMD Ryzen 7 7735HS processor",
      "16GB LPDDR5 RAM",
      "512GB PCIe SSD",
      "AMD Radeon 680M Graphics",
      "Up to 12 hours battery life",
    ],
  },

  // LAPTOPS - ASUS (9 products)
  {
    id: "asus-zenbook-pro-16x-oled",
    name: "ASUS ZenBook Pro 16X OLED",
    brand: "asus",
    category: "laptops",
    price: 349999,
    originalPrice: 399999,
    image: "/products/asus-zenbook-pro-16x-oled.jpg",
    description: "Creator laptop with 4K OLED display and RTX graphics.",
    specs: [
      "16-inch 4K OLED touchscreen",
      "Intel Core i9-13900H processor",
      "32GB DDR5 RAM",
      "1TB PCIe SSD",
      "NVIDIA RTX 4070 8GB",
      "ASUS Dial creative control",
    ],
  },
  {
    id: "asus-rog-strix-g16",
    name: "ASUS ROG Strix G16",
    brand: "asus",
    category: "laptops",
    price: 219999,
    originalPrice: 259999,
    image: "/products/asus-rog-strix-g16.jpg",
    description: "Gaming laptop with RGB lighting and high-performance specs.",
    specs: [
      "16-inch FHD 165Hz display",
      "Intel Core i7-13650HX processor",
      "16GB DDR5 RAM",
      "1TB PCIe SSD",
      "NVIDIA RTX 4060 8GB",
      "ROG Intelligent Cooling",
    ],
  },
  {
    id: "asus-vivobook-s15-oled",
    name: "ASUS Vivobook S15 OLED",
    brand: "asus",
    category: "laptops",
    price: 129999,
    originalPrice: 159999,
    image: "/products/asus-vivobook-s15-oled.jpg",
    description: "Stylish laptop with OLED display and modern design.",
    specs: [
      "15.6-inch FHD OLED display",
      "Intel Core i5-13500H processor",
      "16GB DDR4 RAM",
      "512GB PCIe SSD",
      "Intel Iris Xe Graphics",
      "Up to 9 hours battery life",
    ],
  },
  {
    id: "asus-tuf-gaming-f15",
    name: "ASUS TUF Gaming F15",
    brand: "asus",
    category: "laptops",
    price: 149999,
    originalPrice: 179999,
    image: "/products/asus-tuf-gaming-f15.jpg",
    description: "Durable gaming laptop with military-grade construction.",
    specs: [
      "15.6-inch FHD 144Hz display",
      "Intel Core i5-12500H processor",
      "8GB DDR4 RAM",
      "512GB PCIe SSD",
      "NVIDIA RTX 4050 6GB",
      "MIL-STD-810H durability",
    ],
  },
  {
    id: "asus-zenbook-14-oled",
    name: "ASUS ZenBook 14 OLED",
    brand: "asus",
    category: "laptops",
    price: 159999,
    originalPrice: 189999,
    image: "/products/asus-zenbook-14-oled.jpg",
    description: "Ultra-portable laptop with stunning OLED display.",
    specs: [
      "14-inch 2.8K OLED display",
      "Intel Core i7-1360P processor",
      "16GB LPDDR5 RAM",
      "512GB PCIe SSD",
      "Intel Iris Xe Graphics",
      "Up to 18 hours battery life",
    ],
  },
  {
    id: "asus-rog-zephyrus-g14",
    name: "ASUS ROG Zephyrus G14",
    brand: "asus",
    category: "laptops",
    price: 189999,
    originalPrice: 229999,
    image: "/products/asus-rog-zephyrus-g14.jpg",
    description: "Compact gaming laptop with AMD Ryzen and RTX graphics.",
    specs: [
      "14-inch QHD 165Hz display",
      "AMD Ryzen 9 7940HS processor",
      "16GB DDR5 RAM",
      "1TB PCIe SSD",
      "NVIDIA RTX 4060 8GB",
      "AniMe Matrix LED display",
    ],
  },
  {
    id: "asus-vivobook-15",
    name: "ASUS Vivobook 15",
    brand: "asus",
    category: "laptops",
    price: 79999,
    originalPrice: 99999,
    image: "/products/asus-vivobook-15.jpg",
    description: "Affordable laptop with good performance for everyday use.",
    specs: [
      "15.6-inch FHD display",
      "Intel Core i3-1215U processor",
      "8GB DDR4 RAM",
      "256GB PCIe SSD",
      "Intel UHD Graphics",
      "Up to 6 hours battery life",
    ],
  },
  {
    id: "asus-expertbook-b1500",
    name: "ASUS ExpertBook B1500",
    brand: "asus",
    category: "laptops",
    price: 99999,
    originalPrice: 124999,
    image: "/products/asus-expertbook-b1500.jpg",
    description: "Business laptop with enterprise features and security.",
    specs: [
      "15.6-inch FHD display",
      "Intel Core i5-1235U processor",
      "8GB DDR4 RAM",
      "256GB PCIe SSD",
      "Intel Iris Xe Graphics",
      "TPM 2.0 security chip",
    ],
  },
  {
    id: "asus-rog-flow-x13",
    name: "ASUS ROG Flow X13",
    brand: "asus",
    category: "laptops",
    price: 199999,
    originalPrice: 239999,
    image: "/products/asus-rog-flow-x13.jpg",
    description: "2-in-1 gaming convertible with external GPU support.",
    specs: [
      "13.4-inch 4K touchscreen",
      "AMD Ryzen 9 7940HS processor",
      "16GB LPDDR5 RAM",
      "1TB PCIe SSD",
      "AMD Radeon 780M Graphics",
      "ROG XG Mobile support",
    ],
  },

  // DESKTOP PCs - HP (9 products)
  {
    id: "hp-omen-45l-gaming-desktop",
    name: "HP OMEN 45L Gaming Desktop",
    brand: "hp",
    category: "pcs",
    price: 299999,
    originalPrice: 349999,
    image: "/products/hp-omen-45l-gaming-desktop.jpg",
    description: "High-performance gaming desktop with RTX 4070 and RGB lighting.",
    specs: [
      "Intel Core i7-13700F processor",
      "NVIDIA RTX 4070 12GB graphics",
      "32GB DDR5 RAM",
      "1TB NVMe SSD + 1TB HDD",
      "750W 80+ Gold PSU",
      "Cryo Chamber cooling",
    ],
  },
  {
    id: "hp-pavilion-gaming-tg01",
    name: "HP Pavilion Gaming TG01",
    brand: "hp",
    category: "pcs",
    price: 179999,
    originalPrice: 219999,
    image: "/products/hp-pavilion-gaming-tg01.jpg",
    description: "Entry-level gaming desktop with GTX graphics and modern design.",
    specs: [
      "Intel Core i5-12400F processor",
      "NVIDIA GTX 1660 Super 6GB",
      "16GB DDR4 RAM",
      "512GB NVMe SSD",
      "400W PSU",
      "Tool-less upgrades",
    ],
  },
  {
    id: "hp-elitedesk-800-g9-mini",
    name: "HP EliteDesk 800 G9 Mini",
    brand: "hp",
    category: "pcs",
    price: 149999,
    originalPrice: 179999,
    image: "/products/hp-elitedesk-800-g9-mini.jpg",
    description: "Compact business desktop with enterprise security features.",
    specs: [
      "Intel Core i5-12500T processor",
      "Intel UHD Graphics 770",
      "16GB DDR5 RAM",
      "512GB NVMe SSD",
      "65W power consumption",
      "HP Sure Start Gen7",
    ],
  },
  {
    id: "hp-prodesk-400-g9-sff",
    name: "HP ProDesk 400 G9 SFF",
    brand: "hp",
    category: "pcs",
    price: 89999,
    originalPrice: 114999,
    image: "/products/hp-prodesk-400-g9-sff.jpg",
    description: "Small form factor desktop for business and office use.",
    specs: [
      "Intel Core i3-12100 processor",
      "Intel UHD Graphics 730",
      "8GB DDR4 RAM",
      "256GB NVMe SSD",
      "180W PSU",
      "Multiple connectivity options",
    ],
  },
  {
    id: "hp-z2-mini-g9-workstation",
    name: "HP Z2 Mini G9 Workstation",
    brand: "hp",
    category: "pcs",
    price: 249999,
    originalPrice: 299999,
    image: "/products/hp-z2-mini-g9-workstation.jpg",
    description: "Compact workstation with professional graphics and ISV certification.",
    specs: [
      "Intel Core i7-12700 processor",
      "NVIDIA T1000 4GB professional graphics",
      "32GB DDR5 RAM",
      "1TB NVMe SSD",
      "230W external PSU",
      "ISV certified applications",
    ],
  },
  {
    id: "hp-slim-desktop-s01",
    name: "HP Slim Desktop S01",
    brand: "hp",
    category: "pcs",
    price: 54999,
    originalPrice: 69999,
    image: "/products/hp-slim-desktop-s01.jpg",
    description: "Ultra-compact desktop for basic computing needs.",
    specs: [
      "Intel Celeron J4025 processor",
      "Intel UHD Graphics 600",
      "4GB DDR4 RAM",
      "128GB eMMC storage",
      "65W external PSU",
      "Space-saving design",
    ],
  },
  {
    id: "hp-omen-cryo-chamber-cooling",
    name: "HP OMEN Cryo Chamber Desktop",
    brand: "hp",
    category: "pcs",
    price: 399999,
    originalPrice: 459999,
    image: "/products/hp-omen-cryo-chamber-cooling.jpg",
    description: "Extreme gaming desktop with advanced cooling and RTX 4080.",
    specs: [
      "Intel Core i9-13900KF processor",
      "NVIDIA RTX 4080 16GB graphics",
      "64GB DDR5 RAM",
      "2TB NVMe SSD",
      "1000W 80+ Gold PSU",
      "Cryo Chamber cooling system",
    ],
  },
  {
    id: "hp-all-in-one-24-df",
    name: "HP All-in-One 24-df",
    brand: "hp",
    category: "pcs",
    price: 119999,
    originalPrice: 149999,
    image: "/products/hp-all-in-one-24-df.jpg",
    description: "All-in-one desktop with 24-inch display and modern design.",
    specs: [
      "24-inch FHD IPS display",
      "Intel Core i5-1235U processor",
      "8GB DDR4 RAM",
      "512GB NVMe SSD",
      "Intel Iris Xe Graphics",
      "Built-in webcam and speakers",
    ],
  },
  {
    id: "hp-envy-desktop-te02",
    name: "HP ENVY Desktop TE02",
    brand: "hp",
    category: "pcs",
    price: 159999,
    originalPrice: 189999,
    image: "/products/hp-envy-desktop-te02.jpg",
    description: "Premium desktop with elegant design and powerful performance.",
    specs: [
      "Intel Core i7-12700 processor",
      "NVIDIA GTX 1660 Ti 6GB",
      "16GB DDR4 RAM",
      "1TB NVMe SSD",
      "500W 80+ Bronze PSU",
      "Premium wood finish",
    ],
  },

  // DESKTOP PCs - Lenovo (9 products)
  {
    id: "lenovo-legion-tower-7i",
    name: "Lenovo Legion Tower 7i",
    brand: "lenovo",
    category: "pcs",
    price: 349999,
    originalPrice: 399999,
    image: "/products/lenovo-legion-tower-7i.jpg",
    description: "High-end gaming desktop with RTX 4070 Ti and Legion Coldfront cooling.",
    specs: [
      "Intel Core i7-13700KF processor",
      "NVIDIA RTX 4070 Ti 12GB graphics",
      "32GB DDR5 RAM",
      "1TB NVMe SSD + 2TB HDD",
      "850W 80+ Gold PSU",
      "Legion Coldfront 5.0 cooling",
    ],
  },
  {
    id: "lenovo-ideacentre-gaming-5i",
    name: "Lenovo IdeaCentre Gaming 5i",
    brand: "lenovo",
    category: "pcs",
    price: 199999,
    originalPrice: 239999,
    image: "/products/lenovo-ideacentre-gaming-5i.jpg",
    description: "Mid-range gaming desktop with RTX graphics and RGB lighting.",
    specs: [
      "Intel Core i5-12400F processor",
      "NVIDIA RTX 4060 8GB graphics",
      "16GB DDR4 RAM",
      "512GB NVMe SSD",
      "650W 80+ Bronze PSU",
      "RGB lighting system",
    ],
  },
  {
    id: "lenovo-thinkcentre-m90q-tiny",
    name: "Lenovo ThinkCentre M90q Tiny",
    brand: "lenovo",
    category: "pcs",
    price: 129999,
    originalPrice: 159999,
    image: "/products/lenovo-thinkcentre-m90q-tiny.jpg",
    description: "Ultra-small business desktop with enterprise features.",
    specs: [
      "Intel Core i5-12500T processor",
      "Intel UHD Graphics 770",
      "16GB DDR4 RAM",
      "512GB NVMe SSD",
      "65W power consumption",
      "ThinkShield security",
    ],
  },
  {
    id: "lenovo-thinkstation-p360-tiny",
    name: "Lenovo ThinkStation P360 Tiny",
    brand: "lenovo",
    category: "pcs",
    price: 219999,
    originalPrice: 259999,
    image: "/products/lenovo-thinkstation-p360-tiny.jpg",
    description: "Compact workstation with professional graphics and ISV certification.",
    specs: [
      "Intel Core i7-12700T processor",
      "NVIDIA T1000 4GB professional graphics",
      "32GB DDR5 RAM",
      "1TB NVMe SSD",
      "170W external PSU",
      "ISV certified for CAD/CAM",
    ],
  },
  {
    id: "lenovo-ideacentre-5i",
    name: "Lenovo IdeaCentre 5i",
    brand: "lenovo",
    category: "pcs",
    price: 109999,
    originalPrice: 139999,
    image: "/products/lenovo-ideacentre-5i.jpg",
    description: "Family desktop with good performance for everyday computing.",
    specs: [
      "Intel Core i5-12400 processor",
      "Intel UHD Graphics 730",
      "8GB DDR4 RAM",
      "512GB NVMe SSD",
      "310W PSU",
      "Tool-free chassis access",
    ],
  },
  {
    id: "lenovo-legion-tower-5i",
    name: "Lenovo Legion Tower 5i",
    brand: "lenovo",
    category: "pcs",
    price: 249999,
    originalPrice: 289999,
    image: "/products/lenovo-legion-tower-5i.jpg",
    description: "Gaming desktop with RTX 4060 Ti and Legion cooling system.",
    specs: [
      "Intel Core i5-13400F processor",
      "NVIDIA RTX 4060 Ti 16GB graphics",
      "16GB DDR5 RAM",
      "1TB NVMe SSD",
      "750W 80+ Gold PSU",
      "Legion Coldfront 4.0 cooling",
    ],
  },
  {
    id: "lenovo-thinkcentre-m70s-sff",
    name: "Lenovo ThinkCentre M70s SFF",
    brand: "lenovo",
    category: "pcs",
    price: 89999,
    originalPrice: 114999,
    image: "/products/lenovo-thinkcentre-m70s-sff.jpg",
    description: "Small form factor business desktop with reliable performance.",
    specs: [
      "Intel Core i3-12100 processor",
      "Intel UHD Graphics 730",
      "8GB DDR4 RAM",
      "256GB NVMe SSD",
      "180W PSU",
      "Multiple security features",
    ],
  },
  {
    id: "lenovo-yoga-aio-7",
    name: "Lenovo Yoga AIO 7",
    brand: "lenovo",
    category: "pcs",
    price: 179999,
    originalPrice: 219999,
    image: "/products/lenovo-yoga-aio-7.jpg",
    description: "Premium all-in-one with 4K display and rotating screen.",
    specs: [
      "27-inch 4K IPS touchscreen",
      "AMD Ryzen 7 5800H processor",
      "16GB DDR4 RAM",
      "1TB NVMe SSD",
      "AMD Radeon Graphics",
      "Rotating display mechanism",
    ],
  },
  {
    id: "lenovo-ideacentre-aio-3",
    name: "Lenovo IdeaCentre AIO 3",
    brand: "lenovo",
    category: "pcs",
    price: 99999,
    originalPrice: 124999,
    image: "/products/lenovo-ideacentre-aio-3.jpg",
    description: "Affordable all-in-one desktop for home and office use.",
    specs: [
      "23.8-inch FHD IPS display",
      "AMD Ryzen 5 5500U processor",
      "8GB DDR4 RAM",
      "512GB NVMe SSD",
      "AMD Radeon Graphics",
      "Built-in webcam and speakers",
    ],
  },

  // DESKTOP PCs - ASUS (9 products)
  {
    id: "asus-rog-strix-gt35",
    name: "ASUS ROG Strix GT35",
    brand: "asus",
    category: "pcs",
    price: 399999,
    originalPrice: 459999,
    image: "/products/asus-rog-strix-gt35.jpg",
    description: "Flagship gaming desktop with RTX 4080 and ROG Keystone II.",
    specs: [
      "Intel Core i9-13900KF processor",
      "NVIDIA RTX 4080 16GB graphics",
      "64GB DDR5 RAM",
      "2TB NVMe SSD",
      "1000W 80+ Gold PSU",
      "ROG Keystone II authentication",
    ],
  },
  {
    id: "asus-rog-strix-g15dk",
    name: "ASUS ROG Strix G15DK",
    brand: "asus",
    category: "pcs",
    price: 229999,
    originalPrice: 269999,
    image: "/products/asus-rog-strix-g15dk.jpg",
    description: "AMD-powered gaming desktop with RTX graphics and Aura Sync RGB.",
    specs: [
      "AMD Ryzen 7 7700X processor",
      "NVIDIA RTX 4060 Ti 16GB graphics",
      "16GB DDR5 RAM",
      "1TB NVMe SSD",
      "750W 80+ Gold PSU",
      "Aura Sync RGB lighting",
    ],
  },
  {
    id: "asus-vivopc-x",
    name: "ASUS VivoPC X",
    brand: "asus",
    category: "pcs",
    price: 89999,
    originalPrice: 114999,
    image: "/products/asus-vivopc-x.jpg",
    description: "Compact desktop with modern design and good performance.",
    specs: [
      "Intel Core i5-1240P processor",
      "Intel Iris Xe Graphics",
      "8GB DDR4 RAM",
      "512GB NVMe SSD",
      "90W external PSU",
      "Ultra-compact form factor",
    ],
  },
  {
    id: "asus-expertcenter-d7-sff",
    name: "ASUS ExpertCenter D7 SFF",
    brand: "asus",
    category: "pcs",
    price: 119999,
    originalPrice: 149999,
    image: "/products/asus-expertcenter-d7-sff.jpg",
    description: "Business desktop with enterprise security and management features.",
    specs: [
      "Intel Core i5-12500 processor",
      "Intel UHD Graphics 770",
      "16GB DDR4 RAM",
      "512GB NVMe SSD",
      "300W 80+ Bronze PSU",
      "ASUS Control Center Express",
    ],
  },
  {
    id: "asus-rog-strix-g10dk",
    name: "ASUS ROG Strix G10DK",
    brand: "asus",
    category: "pcs",
    price: 179999,
    originalPrice: 219999,
    image: "/products/asus-rog-strix-g10dk.jpg",
    description: "Mid-range gaming desktop with AMD Ryzen and RTX graphics.",
    specs: [
      "AMD Ryzen 5 7600X processor",
      "NVIDIA RTX 4060 8GB graphics",
      "16GB DDR5 RAM",
      "512GB NVMe SSD",
      "650W 80+ Bronze PSU",
      "Tool-free upgrades",
    ],
  },
  {
    id: "asus-proart-station-pd5",
    name: "ASUS ProArt Station PD5",
    brand: "asus",
    category: "pcs",
    price: 349999,
    originalPrice: 399999,
    image: "/products/asus-proart-station-pd5.jpg",
    description: "Creator workstation with professional graphics and ISV certification.",
    specs: [
      "Intel Core i9-13900 processor",
      "NVIDIA RTX A4000 16GB professional graphics",
      "64GB DDR5 RAM",
      "2TB NVMe SSD",
      "850W 80+ Gold PSU",
      "ISV certified for creative apps",
    ],
  },
  {
    id: "asus-mini-pc-pn64",
    name: "ASUS Mini PC PN64",
    brand: "asus",
    category: "pcs",
    price: 79999,
    originalPrice: 99999,
    image: "/products/asus-mini-pc-pn64.jpg",
    description: "Ultra-compact mini PC for space-constrained environments.",
    specs: [
      "AMD Ryzen 7 6800U processor",
      "AMD Radeon 680M Graphics",
      "16GB DDR5 RAM",
      "512GB NVMe SSD",
      "90W external PSU",
      "Multiple display outputs",
    ],
  },
  {
    id: "asus-zen-aio-24",
    name: "ASUS Zen AiO 24",
    brand: "asus",
    category: "pcs",
    price: 149999,
    originalPrice: 179999,
    image: "/products/asus-zen-aio-24.jpg",
    description: "All-in-one desktop with elegant design and good performance.",
    specs: [
      "23.8-inch FHD IPS display",
      "Intel Core i5-1235U processor",
      "8GB DDR4 RAM",
      "512GB NVMe SSD",
      "Intel Iris Xe Graphics",
      "Wireless keyboard and mouse",
    ],
  },
  {
    id: "asus-rog-nuc",
    name: "ASUS ROG NUC",
    brand: "asus",
    category: "pcs",
    price: 199999,
    originalPrice: 239999,
    image: "/products/asus-rog-nuc.jpg",
    description: "Compact gaming PC with desktop-class performance.",
    specs: [
      "Intel Core i7-13700H processor",
      "NVIDIA RTX 4060 8GB graphics",
      "32GB DDR5 RAM",
      "1TB NVMe SSD",
      "330W external PSU",
      "ROG Aura Sync RGB",
    ],
  },

  // MONITORS (9 products)
  {
    id: "samsung-odyssey-g9-49",
    name: 'Samsung Odyssey G9 49" Curved Gaming Monitor',
    brand: "samsung",
    category: "monitors",
    price: 179999,
    originalPrice: 219999,
    image: "/products/samsung-odyssey-g9-49.jpg",
    description: "Ultra-wide curved gaming monitor with 240Hz refresh rate and HDR1000.",
    specs: [
      "49-inch Dual QHD (5120x1440) curved display",
      "240Hz refresh rate with 1ms response time",
      "HDR1000 with Quantum Dot technology",
      "AMD FreeSync Premium Pro",
      "1000R curvature for immersive gaming",
      "RGB lighting and height-adjustable stand",
    ],
  },
  {
    id: "lg-ultragear-27gn950",
    name: 'LG UltraGear 27GN950 27" 4K Gaming Monitor',
    brand: "lg",
    category: "monitors",
    price: 89999,
    originalPrice: 109999,
    image: "/products/lg-ultragear-27gn950.jpg",
    description: "4K gaming monitor with 144Hz refresh rate and NVIDIA G-SYNC compatibility.",
    specs: [
      "27-inch 4K UHD (3840x2160) IPS display",
      "144Hz refresh rate with 1ms response time",
      "HDR600 with 98% DCI-P3 color gamut",
      "NVIDIA G-SYNC Compatible",
      "USB-C connectivity with 60W power delivery",
      "Height and tilt adjustable stand",
    ],
  },
  {
    id: "dell-ultrasharp-u2723qe",
    name: 'Dell UltraSharp U2723QE 27" 4K Monitor',
    brand: "dell",
    category: "monitors",
    price: 79999,
    originalPrice: 99999,
    image: "/products/dell-ultrasharp-u2723qe.jpg",
    description: "Professional 4K monitor with USB-C hub and color accuracy.",
    specs: [
      "27-inch 4K UHD (3840x2160) IPS display",
      "60Hz refresh rate with 5ms response time",
      "99% sRGB and 95% DCI-P3 color accuracy",
      "USB-C hub with 90W power delivery",
      "Daisy chain capability",
      "Height, tilt, swivel, and pivot adjustments",
    ],
  },
  {
    id: "asus-proart-pa278qv",
    name: 'ASUS ProArt PA278QV 27" Professional Monitor',
    brand: "asus",
    category: "monitors",
    price: 54999,
    originalPrice: 69999,
    image: "/products/asus-proart-pa278qv.jpg",
    description: "Color-accurate monitor for creative professionals with factory calibration.",
    specs: [
      "27-inch QHD (2560x1440) IPS display",
      "75Hz refresh rate with 5ms response time",
      "100% sRGB and Rec. 709 color accuracy",
      "Factory pre-calibrated with Delta E < 2",
      "USB-C connectivity with 65W power delivery",
      "ProArt Palette software included",
    ],
  },
  {
    id: "acer-predator-x34gs",
    name: 'Acer Predator X34GS 34" Curved Gaming Monitor',
    brand: "acer",
    category: "monitors",
    price: 119999,
    originalPrice: 149999,
    image: "/products/acer-predator-x34gs.jpg",
    description: "Ultra-wide curved gaming monitor with 180Hz refresh rate and G-SYNC.",
    specs: [
      "34-inch UWQHD (3440x1440) curved IPS display",
      "180Hz refresh rate with 1ms response time",
      "HDR400 with 90% DCI-P3 color gamut",
      "NVIDIA G-SYNC Compatible",
      "1900R curvature for immersive gaming",
      "RGB lighting and ergonomic stand",
    ],
  },
  {
    id: "hp-omen-27c",
    name: 'HP OMEN 27c 27" Curved Gaming Monitor',
    brand: "hp",
    category: "monitors",
    price: 44999,
    originalPrice: 59999,
    image: "/products/hp-omen-27c.jpg",
    description: "Curved gaming monitor with 165Hz refresh rate and AMD FreeSync.",
    specs: [
      "27-inch QHD (2560x1440) curved VA display",
      "165Hz refresh rate with 1ms response time",
      "AMD FreeSync Premium technology",
      "1500R curvature for gaming immersion",
      "Height and tilt adjustable stand",
      "OMEN Command Center software",
    ],
  },
  {
    id: "benq-pd3220u",
    name: 'BenQ PD3220U 32" 4K Designer Monitor',
    brand: "benq",
    category: "monitors",
    price: 99999,
    originalPrice: 124999,
    image: "/products/benq-pd3220u.jpg",
    description: "Large 4K monitor for designers with Thunderbolt 3 and color accuracy.",
    specs: [
      "32-inch 4K UHD (3840x2160) IPS display",
      "60Hz refresh rate with 5ms response time",
      "95% DCI-P3 and 100% sRGB color accuracy",
      "Thunderbolt 3 with 85W power delivery",
      "Hardware calibration support",
      "Hotkey Puck G2 for easy control",
    ],
  },
  {
    id: "msi-optix-mag274qrf",
    name: 'MSI Optix MAG274QRF 27" Gaming Monitor',
    brand: "msi",
    category: "monitors",
    price: 64999,
    originalPrice: 79999,
    image: "/products/msi-optix-mag274qrf.jpg",
    description: "Fast gaming monitor with 165Hz refresh rate and RGB lighting.",
    specs: [
      "27-inch QHD (2560x1440) IPS display",
      "165Hz refresh rate with 1ms response time",
      "HDR400 with wide color gamut",
      "AMD FreeSync Premium technology",
      "Mystic Light RGB lighting",
      "Gaming OSD app for easy settings",
    ],
  },
  {
    id: "viewsonic-vp2468",
    name: 'ViewSonic VP2468 24" Professional Monitor',
    brand: "viewsonic",
    category: "monitors",
    price: 39999,
    originalPrice: 49999,
    image: "/products/viewsonic-vp2468.jpg",
    description: "Professional monitor with color accuracy and ergonomic design.",
    specs: [
      "24-inch FHD (1920x1080) IPS display",
      "60Hz refresh rate with 5ms response time",
      "100% sRGB color accuracy",
      "Hardware calibration support",
      "USB-C connectivity with power delivery",
      "Height, tilt, swivel, and pivot adjustments",
    ],
  },

  // PRINTERS & TONERS (9 products)
  {
    id: "hp-laserjet-pro-m404dn",
    name: "HP LaserJet Pro M404dn Printer",
    brand: "hp",
    category: "printers",
    price: 34999,
    originalPrice: 42999,
    image: "/products/hp-laserjet-pro-m404dn.jpg",
    description: "Fast monochrome laser printer for small offices with duplex printing.",
    specs: [
      "Monochrome laser printing technology",
      "Print speed up to 38 pages per minute",
      "Automatic duplex printing",
      "250-sheet input tray capacity",
      "Ethernet and USB connectivity",
      "Monthly duty cycle up to 80,000 pages",
    ],
  },
  {
    id: "canon-pixma-g3020",
    name: "Canon PIXMA G3020 All-in-One Printer",
    brand: "canon",
    category: "printers",
    price: 24999,
    originalPrice: 31999,
    image: "/products/canon-pixma-g3020.jpg",
    description: "Ink tank all-in-one printer with wireless connectivity and low running costs.",
    specs: [
      "Color inkjet printing technology",
      "Print, scan, and copy functions",
      "Wireless and USB connectivity",
      "Borderless printing up to A4 size",
      "High-yield ink bottles included",
      "Print speed up to 9.1 ipm (color)",
    ],
  },
  {
    id: "epson-ecotank-l3250",
    name: "Epson EcoTank L3250 All-in-One Printer",
    brand: "epson",
    category: "printers",
    price: 29999,
    originalPrice: 37999,
    image: "/products/epson-ecotank-l3250.jpg",
    description: "EcoTank printer with ultra-low-cost printing and wireless connectivity.",
    specs: [
      "Color inkjet printing with EcoTank technology",
      "Print, scan, and copy functions",
      "Wi-Fi and Wi-Fi Direct connectivity",
      "Borderless printing up to A4 size",
      "Ultra-high-yield ink bottles",
      "Print speed up to 10 ppm (black)",
    ],
  },
  {
    id: "brother-dcp-l2540dw",
    name: "Brother DCP-L2540DW Laser Printer",
    brand: "brother",
    category: "printers",
    price: 39999,
    originalPrice: 49999,
    image: "/products/brother-dcp-l2540dw.jpg",
    description: "Compact laser all-in-one with wireless connectivity and duplex printing.",
    specs: [
      "Monochrome laser printing technology",
      "Print, scan, and copy functions",
      "Wireless and USB connectivity",
      "Automatic duplex printing",
      "250-sheet paper capacity",
      "Print speed up to 30 ppm",
    ],
  },
  {
    id: "hp-color-laserjet-pro-m255dw",
    name: "HP Color LaserJet Pro M255dw",
    brand: "hp",
    category: "printers",
    price: 54999,
    originalPrice: 69999,
    image: "/products/hp-color-laserjet-pro-m255dw.jpg",
    description: "Compact color laser printer with wireless connectivity and security features.",
    specs: [
      "Color laser printing technology",
      "Print speed up to 22 ppm (color)",
      "Automatic duplex printing",
      "250-sheet input tray",
      "Wi-Fi and Ethernet connectivity",
      "HP Smart app compatibility",
    ],
  },
  {
    id: "canon-imageclass-mf3010",
    name: "Canon imageCLASS MF3010 Laser Printer",
    brand: "canon",
    category: "printers",
    price: 19999,
    originalPrice: 24999,
    image: "/products/canon-imageclass-mf3010.jpg",
    description: "Basic monochrome laser all-in-one for home and small office use.",
    specs: [
      "Monochrome laser printing technology",
      "Print, scan, and copy functions",
      "USB connectivity",
      "150-sheet paper capacity",
      "Print speed up to 18 ppm",
      "Compact desktop design",
    ],
  },
  {
    id: "hp-toner-cf217a",
    name: "HP 17A (CF217A) Black Toner Cartridge",
    brand: "hp",
    category: "printers",
    price: 8999,
    originalPrice: 11999,
    image: "/products/hp-toner-cf217a.jpg",
    description: "Original HP toner cartridge for LaserJet Pro M102/M130 series printers.",
    specs: [
      "Black toner cartridge",
      "Page yield approximately 1,600 pages",
      "Compatible with HP LaserJet Pro M102/M130 series",
      "Original HP quality and reliability",
      "Easy installation process",
      "Consistent print quality",
    ],
  },
  {
    id: "canon-ink-pg-745xl",
    name: "Canon PG-745XL Black Ink Cartridge",
    brand: "canon",
    category: "printers",
    price: 3999,
    originalPrice: 4999,
    image: "/products/canon-ink-pg-745xl.jpg",
    description: "High-yield black ink cartridge for Canon PIXMA printers.",
    specs: [
      "Black ink cartridge",
      "High-yield capacity",
      "Compatible with PIXMA MG2470/MG2570/MG2577 series",
      "Page yield approximately 400 pages",
      "Original Canon quality",
      "Easy installation",
    ],
  },
  {
    id: "epson-ink-t664-set",
    name: "Epson T664 4-Color Ink Bottle Set",
    brand: "epson",
    category: "printers",
    price: 5999,
    originalPrice: 7999,
    image: "/products/epson-ink-t664-set.jpg",
    description: "Complete 4-color ink bottle set for Epson EcoTank printers.",
    specs: [
      "4-color ink bottle set (Black, Cyan, Magenta, Yellow)",
      "Compatible with EcoTank L120/L220/L360/L380 series",
      "High page yield up to 4,000 pages (black)",
      "Ultra-low-cost printing",
      "Original Epson quality",
      "Easy refill process",
    ],
  },

  // TABLETS (9 products)
  {
    id: "ipad-pro-12-9-m4",
    name: "iPad Pro 12.9-inch (M4)",
    brand: "apple",
    category: "tablets",
    price: 179999,
    originalPrice: 199999,
    image: "/products/ipad-pro-12-9-m4.jpg",
    description: "Most advanced iPad with M4 chip, Liquid Retina XDR display, and Apple Pencil Pro support.",
    specs: [
      "12.9-inch Liquid Retina XDR display",
      "Apple M4 chip with 10-core CPU",
      "12MP Wide and 10MP Ultra Wide cameras",
      "Thunderbolt/USB 4 connectivity",
      "Apple Pencil Pro and Magic Keyboard support",
      "Up to 10 hours battery life",
    ],
  },
  {
    id: "ipad-air-11-m4",
    name: "iPad Air 11-inch (M4)",
    brand: "apple",
    category: "tablets",
    price: 89999,
    originalPrice: 109999,
    image: "/products/ipad-air-11-m4.jpg",
    description: "Powerful and portable iPad with M4 chip and stunning Liquid Retina display.",
    specs: [
      "11-inch Liquid Retina display",
      "Apple M4 chip with 9-core CPU",
      "12MP Wide camera",
      "USB-C connectivity",
      "Apple Pencil Pro and Magic Keyboard support",
      "Up to 10 hours battery life",
    ],
  },
  {
    id: "samsung-galaxy-tab-s10-ultra",
    name: "Samsung Galaxy Tab S10 Ultra",
    brand: "samsung",
    category: "tablets",
    price: 149999,
    originalPrice: 169999,
    image: "/products/samsung-galaxy-tab-s10-ultra.jpg",
    description: "Premium Android tablet with large display, S Pen, and desktop-class performance.",
    specs: [
      "14.6-inch Dynamic AMOLED 2X display",
      "Snapdragon 8 Gen 3 processor",
      "13MP + 8MP dual rear cameras",
      "S Pen included with advanced features",
      "DeX mode for desktop experience",
      "Up to 16 hours battery life",
    ],
  },
  {
    id: "samsung-galaxy-tab-s10-plus",
    name: "Samsung Galaxy Tab S10+",
    brand: "samsung",
    category: "tablets",
    price: 119999,
    originalPrice: 139999,
    image: "/products/samsung-galaxy-tab-s10-plus.jpg",
    description: "Large Android tablet with S Pen and premium features for productivity.",
    specs: [
      "12.4-inch Dynamic AMOLED 2X display",
      "Snapdragon 8 Gen 3 processor",
      "13MP + 8MP dual rear cameras",
      "S Pen included",
      "12GB RAM, 256GB storage",
      "Up to 15 hours battery life",
    ],
  },
  {
    id: "microsoft-surface-pro-11",
    name: "Microsoft Surface Pro 11",
    brand: "microsoft",
    category: "tablets",
    price: 159999,
    originalPrice: 179999,
    image: "/products/microsoft-surface-pro-11.jpg",
    description: "2-in-1 tablet with laptop performance, running full Windows 11.",
    specs: [
      "13-inch PixelSense Flow display",
      "Snapdragon X Elite processor",
      "10MP rear and 5MP front cameras",
      "Surface Pen and Type Cover support",
      "Full Windows 11 experience",
      "Up to 14 hours battery life",
    ],
  },
  {
    id: "lenovo-tab-p12-pro",
    name: "Lenovo Tab P12 Pro",
    brand: "lenovo",
    category: "tablets",
    price: 79999,
    originalPrice: 99999,
    image: "/products/lenovo-tab-p12-pro.jpg",
    description: "Premium Android tablet with OLED display and productivity features.",
    specs: [
      "12.6-inch 2.5K OLED display",
      "MediaTek Dimensity 7050 processor",
      "13MP + 5MP dual rear cameras",
      "Lenovo Precision Pen 3 support",
      "8GB RAM, 256GB storage",
      "JBL quad speakers with Dolby Atmos",
    ],
  },
  {
    id: "huawei-matepad-pro-13-2",
    name: "Huawei MatePad Pro 13.2",
    brand: "huawei",
    category: "tablets",
    price: 109999,
    originalPrice: 129999,
    image: "/products/huawei-matepad-pro-13-2.jpg",
    description: "Large premium tablet with OLED display and M-Pencil support.",
    specs: [
      "13.2-inch OLED FullView display",
      "Kirin 9000s processor",
      "13MP + 8MP dual rear cameras",
      "Huawei M-Pencil (3rd Gen) support",
      "12GB RAM, 512GB storage",
      "HarmonyOS 4.2",
    ],
  },
  {
    id: "xiaomi-pad-6-pro",
    name: "Xiaomi Pad 6 Pro",
    brand: "xiaomi",
    category: "tablets",
    price: 64999,
    originalPrice: 79999,
    image: "/products/xiaomi-pad-6-pro.jpg",
    description: "High-performance Android tablet with 144Hz display and Snapdragon processor.",
    specs: [
      "11-inch 2.8K LCD display with 144Hz",
      "Snapdragon 8+ Gen 1 processor",
      "50MP + 2MP dual rear cameras",
      "Xiaomi Smart Pen support",
      "8GB RAM, 256GB storage",
      "8840mAh battery with 67W fast charging",
    ],
  },
  {
    id: "amazon-fire-max-11",
    name: "Amazon Fire Max 11",
    brand: "amazon",
    category: "tablets",
    price: 34999,
    originalPrice: 42999,
    image: "/products/amazon-fire-max-11.jpg",
    description: "Large entertainment tablet with Alexa built-in and long battery life.",
    specs: [
      "11-inch 2K display",
      "Octa-core 2.2GHz processor",
      "8MP rear and 8MP front cameras",
      "Alexa built-in",
      "4GB RAM, 64GB storage",
      "Up to 14 hours battery life",
    ],
  },

  // HOME APPLIANCES (existing products with discounts)
  {
    id: "samsung-refrigerator-rf28t5001sr",
    name: "Samsung 28 cu. ft. French Door Refrigerator",
    brand: "samsung",
    category: "appliances",
    price: 264999,
    originalPrice: 299999,
    image: "/products/samsung-refrigerator-rf28t5001sr.jpg",
    description: "Spacious French door refrigerator with Twin Cooling Plus technology and FlexZone drawer.",
    specs: [
      "28 cu. ft. capacity",
      "Twin Cooling Plus technology",
      "FlexZone drawer with 5 temperature settings",
      "Ice and water dispenser",
      "ENERGY STAR certified",
    ],
  },
  {
    id: "lg-washer-dryer-wm3900hwa",
    name: "LG 4.5 cu. ft. Front Load Washer",
    brand: "lg",
    category: "appliances",
    price: 124999,
    originalPrice: 149999,
    image: "/products/lg-washer-dryer-wm3900hwa.jpg",
    description: "High-efficiency front load washer with TurboWash 360 technology and steam cleaning.",
    specs: [
      "4.5 cu. ft. capacity",
      "TurboWash 360 technology",
      "Steam cleaning function",
      "14 wash cycles",
      "ENERGY STAR certified",
    ],
  },
  {
    id: "dyson-vacuum-v15-detect",
    name: "Dyson V15 Detect Cordless Vacuum",
    brand: "dyson",
    category: "appliances",
    price: 99999,
    originalPrice: 124999,
    image: "/products/dyson-vacuum-v15-detect.jpg",
    description: "Advanced cordless vacuum with laser dust detection and intelligent suction adjustment.",
    specs: [
      "Laser dust detection",
      "Up to 60 minutes run time",
      "5-stage filtration system",
      "LCD screen with real-time reports",
      "Converts to handheld",
    ],
  },
  {
    id: "whirlpool-dishwasher-wdt750sakz",
    name: "Whirlpool Built-In Dishwasher",
    brand: "whirlpool",
    category: "appliances",
    price: 89999,
    originalPrice: 109999,
    image: "/products/whirlpool-dishwasher-wdt750sakz.jpg",
    description: "Quiet and efficient built-in dishwasher with multiple wash cycles and stainless steel interior.",
    specs: [
      "15 place setting capacity",
      "6 wash cycles including Heavy and Quick",
      "Stainless steel interior",
      "Quiet operation at 47 dBA",
      "ENERGY STAR certified",
    ],
  },
  {
    id: "ge-microwave-jvm3160rfss",
    name: "GE Over-the-Range Microwave",
    brand: "ge",
    category: "appliances",
    price: 54999,
    originalPrice: 69999,
    image: "/products/ge-microwave-jvm3160rfss.jpg",
    description: "Space-saving over-the-range microwave with powerful ventilation and convenient features.",
    specs: [
      "1.6 cu. ft. capacity",
      "1000 watts cooking power",
      "300 CFM ventilation system",
      "Sensor cooking controls",
      "Stainless steel finish",
    ],
  },
  {
    id: "kitchenaid-stand-mixer-ksm150pser",
    name: "KitchenAid Artisan Stand Mixer",
    brand: "kitchenaid",
    category: "appliances",
    price: 64999,
    originalPrice: 79999,
    image: "/products/kitchenaid-stand-mixer-ksm150pser.jpg",
    description: "Professional-grade stand mixer perfect for baking and cooking enthusiasts.",
    specs: [
      "5-quart stainless steel bowl",
      "10 mixing speeds",
      "Tilt-head design",
      "Multiple attachment options",
      "Available in various colors",
    ],
  },

  // ACCESSORIES (existing products with discounts)
  {
    id: "airpods-pro-2",
    name: "AirPods Pro (2nd Gen)",
    brand: "apple",
    category: "accessories",
    price: 34999,
    originalPrice: 39999,
    image: "/products/airpods-pro-2.jpg",
    description: "Premium wireless earbuds with active noise cancellation and spatial audio.",
    specs: [
      "Active Noise Cancellation",
      "Transparency mode",
      "Spatial audio with head tracking",
      "Up to 6 hours listening time",
      "MagSafe charging case",
    ],
  },
  {
    id: "nintendo-switch-2",
    name: "Nintendo Switch 2",
    brand: "nintendo",
    category: "accessories",
    price: 49999,
    originalPrice: 59999,
    image: "/products/nintendo-switch-2.jpg",
    description: "Next-generation gaming console with enhanced performance and better graphics.",
    specs: [
      "8-inch OLED display",
      "Custom NVIDIA Tegra processor",
      "128GB internal storage",
      "Enhanced Joy-Con controllers",
      "4K docked gaming support",
    ],
  },
]

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

export const shuffledProducts = shuffleArray(products)

export const DELIVERY_POLICY = {
  FREE_DELIVERY_THRESHOLD: 50000,
  STANDARD_DELIVERY_FEE: 500,
  EXPRESS_DELIVERY_FEE: 1000,
}

export function calculateDeliveryFee(orderTotal: number): number {
  return orderTotal >= DELIVERY_POLICY.FREE_DELIVERY_THRESHOLD ? 0 : DELIVERY_POLICY.STANDARD_DELIVERY_FEE
}
